name: AInet Symbolic Regression

 github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-primer
 gfm_quirks: paragraph_end

footer-links:
  dribbble:
  email: guilherme.seidyo@gmail.com
  facebook:
  flickr:
  github:
  instagram:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
  
google_analytics:
